### PR TITLE
Implement tab-eating indent plugin

### PR DESCRIPTION
**Pull request by seidtgeist**
At the moment indent only replaces leading tab indentation w/ the plugin value.
In the future it definitely needs to support from-space indentation, too!

This needs more work but I'm warming up the pull request goblins for this one!

### CODE REVIEW

**Comment by seidtgeist** [comment]
Anyway, this already helped me in a project multiple people are working on. Observations:
- Tabs and spaces in the same file. Visually that doesn't help because tab width = 2 looks fine.
- Syntux conversion: Boom, all problems solved. Saved me time and didn't fuck up existing code.

Learning: A stupid first version of a plugin that doesn't break custom style is worth more than a complex plugin that breaks style.

**Comment by seidtgeist** [comment]
For the record I believe that ultimately different complex indentation styles can only be solved through:
- Custom indent plugins
- A combination of indent & specific other plugins (i.e. indentVar for double-indenting subsequent decls in multi-line var statements)

**Comment by seidtgeist** [comment]
Updated this to work with the new token API.

**Comment by seidtgeist** [comment]
I renamed this plugin to replaceTabs. indent needs more love than I am willing to offer right now ;'-)

@felixge, @klipstein: I would like to merge this now. Please +/-1 this.

**Comment by klipstein** [comment]
Go for it.

**Comment by seidtgeist** [comment]
> Go for it.

DOES NOT COMPUTE

**Pull request merged**
